"""initial migration

Revision ID: 553f03ce6a47
Revises: 
Create Date: 2020-08-13 14:26:28.147378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553f03ce6a47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_description'), 'topic', ['description'], unique=False)
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('up_votes', sa.Integer(), nullable=True),
    sa.Column('down_votes', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_down_votes'), 'question', ['down_votes'], unique=False)
    op.create_index(op.f('ix_question_text'), 'question', ['text'], unique=True)
    op.create_index(op.f('ix_question_up_votes'), 'question', ['up_votes'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('up_votes', sa.Integer(), nullable=True),
    sa.Column('down_votes', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_down_votes'), 'answer', ['down_votes'], unique=False)
    op.create_index(op.f('ix_answer_text'), 'answer', ['text'], unique=True)
    op.create_index(op.f('ix_answer_up_votes'), 'answer', ['up_votes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_up_votes'), table_name='answer')
    op.drop_index(op.f('ix_answer_text'), table_name='answer')
    op.drop_index(op.f('ix_answer_down_votes'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_up_votes'), table_name='question')
    op.drop_index(op.f('ix_question_text'), table_name='question')
    op.drop_index(op.f('ix_question_down_votes'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_index(op.f('ix_topic_description'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
