"""validate topic name is unique

Revision ID: 61d2e151ba72
Revises: 553f03ce6a47
Create Date: 2020-08-14 14:03:44.821405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d2e151ba72'
down_revision = '553f03ce6a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topic_name', table_name='topic')
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.create_index('ix_topic_name', 'topic', ['name'], unique=False)
    # ### end Alembic commands ###
